# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U pip setuptools wheel

COPY pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir --timeout 120 --retries 10 \
    fastapi \
    "uvicorn[standard]" \
    python-multipart \
    pandas \
    numpy \
    scikit-learn \
    matplotlib \
    joblib \
    requests \
    lightgbm \
    catboost \
    shap \
    python-docx \
    pyyaml \
    openpyxl

COPY churnlib /app/churnlib
COPY app /app/app

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8000"]