FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U pip

COPY pyproject.toml /app/pyproject.toml
COPY churnlib /app/churnlib
COPY app /app/app

RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    python-multipart \
    pandas \
    numpy \
    scikit-learn \
    matplotlib \
    joblib \
    pyarrow \
    requests \
    lightgbm \
    catboost \
    shap

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8000"]